### ISSUE TITLE
error ern npm run dev frontend

### ISSUE THREAD

**Issue by darkcam** [Vinix-Code-Dev/curso-api-whatsapp-frontend#13]
buenas tarde 

a la hora de arrancar el npm run dev del frontend me sale esta errror

node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\laragon\www\imbawapp_lr\curso-api-whatsapp-frontend\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\laragon\www\imbawapp_lr\curso-api-whatsapp-frontend\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\laragon\www\imbawapp_lr\curso-api-whatsapp-frontend\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\laragon\www\imbawapp_lr\curso-api-whatsapp-frontend\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\laragon\www\imbawapp_lr\curso-api-whatsapp-frontend\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\laragon\www\imbawapp_lr\curso-api-whatsapp-frontend\node_modules\webpack\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\laragon\www\imbawapp_lr\curso-api-whatsapp-frontend\node_modules\webpack\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (C:\laragon\www\imbawapp_lr\curso-api-whatsapp-frontend\node_modules\webpack\node_modules\loader-runner\lib\LoaderRunner.js:205:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.1

cómo puedo solucionarlo

**Comment by vinixcode** [comment]
Hola @darkcam te sugiero que uses la version 16 de NodeJS. Puedes instalar nvm para tener distintas versiones de node en el mismo equipo.

**Comment by vinixcode** [comment]
Cerrando por inactividad.
