### ISSUE TITLE
error # clase 12. Instalación de Frontend

### ISSUE THREAD

**Issue by leandrogr21** [Vinix-Code-Dev/curso-api-whatsapp-frontend#46]
Buenas tardes, estoy en la clase 12 del front end, ya cloné su repositorio, ya le di, npm install, no hubo problemas pero al correr el frame si lo hubo ya que corro el comando:
npm run dev.

y genera este error:
* Client █████████████████████████ building (10%) 1/2 modules 1 active
 node_modules\webpack-hot-middleware\client.js
 ERROR  Error: error:0308010C:digital envelope routines::unsupported                                                            17:39:35  
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Apache24\htdocs\api-whatsapp-frontend-master\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Apache24\htdocs\api-whatsapp-frontend-master\node_modules\webpack\lib\NormalModule.js:417:16)      
    at handleParseError (C:\Apache24\htdocs\api-whatsapp-frontend-master\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Apache24\htdocs\api-whatsapp-frontend-master\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Apache24\htdocs\api-whatsapp-frontend-master\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Apache24\htdocs\api-whatsapp-frontend-master\node_modules\webpack\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Apache24\htdocs\api-whatsapp-frontend-master\node_modules\webpack\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Apache24\htdocs\api-whatsapp-frontend-master\node_modules\webpack\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at C:\Apache24\htdocs\api-whatsapp-frontend-master\node_modules\webpack\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (C:\Apache24\htdocs\api-whatsapp-frontend-master\node_modules\webpack\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (C:\Apache24\htdocs\api-whatsapp-frontend-master\node_modules\webpack\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (C:\Apache24\htdocs\api-whatsapp-frontend-master\node_modules\webpack\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\Apache24\htdocs\api-whatsapp-frontend-master\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)    at C:\Apache24\htdocs\api-whatsapp-frontend-master\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at C:\Apache24\htdocs\api-whatsapp-frontend-master\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)

node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Apache24\htdocs\api-whatsapp-frontend-master\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Apache24\htdocs\api-whatsapp-frontend-master\node_modules\webpack\lib\NormalModule.js:417:16)      
    at handleParseError (C:\Apache24\htdocs\api-whatsapp-frontend-master\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Apache24\htdocs\api-whatsapp-frontend-master\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Apache24\htdocs\api-whatsapp-frontend-master\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Apache24\htdocs\api-whatsapp-frontend-master\node_modules\webpack\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Apache24\htdocs\api-whatsapp-frontend-master\node_modules\webpack\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (C:\Apache24\htdocs\api-whatsapp-frontend-master\node_modules\webpack\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\Apache24\htdocs\api-whatsapp-frontend-master\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)    at C:\Apache24\htdocs\api-whatsapp-frontend-master\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at C:\Apache24\htdocs\api-whatsapp-frontend-master\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Quisiera saber que versión de node usaron ya que la tengo es la actual :
C:\Users\Siicsa>node -v
v18.14.2

C:\Users\Siicsa>npm -v
8.14.0

Si es por la versión de node, de la cual creo que es así, cual versión me recomienda??

Gracias.

**Comment by BCIPRIANR** [comment]
Hola compañero buen dia me paso el mismo error tuyo y en efecto era la version con nvm instale la version 16.19.0 que es la que recomiendan y fluyo todo por si te sirve  
![image](https://user-images.githubusercontent.com/124621666/221222181-92e2ded6-80ae-4600-850a-c66d84481d3d.png)

**Comment by vinixcode** [comment]
Es correcto lo que dice @BCIPRIANR . Por favor intenta instalando nvm y poniendo a correr la version 16 de node https://github.com/nvm-sh/nvm

Saludos
